server:
  port: 8888

spring:
  cloud:
    gateway:
      routes:
      - id: employeeModule
        uri: http://localhost:8084/
        predicates:
        - Path=/employee/**
      - id: employeeDetailsModule
        uri: http://localhost:8083/
        predicates:
        - Path=/employeeDetails/**
