server:
 port: 8084
 
spring:
 datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  h2:
   console:
    enabled: false
 jpa:
  show: 
   sql: true
---
spring:
 profiles: default
 application:
   name: employee
 cloud:
   config:
      uri: http://localhost:8081
      label: develop
      enabled: true
